{% set version = "0.12.1-20160607" %}

package:
  name: json-c
  version: {{ version.split('-')[0] }}

source:
  url: https://github.com/json-c/json-c/archive/json-c-{{ version }}.tar.gz
  sha256: 989e09b99ded277a0a651cd18b81fcb76885fea08769d7a21b6da39fb8a34816

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool

test:
  commands:
    - test -f ${PREFIX}/lib/libjson-c.a
    - test -f ${PREFIX}/lib/libjson-c${SHLIB_EXT}

about:
  home: https://github.com/json-c/json-c/wiki
  license: MIT
  license_file: COPYING
  summary: 'A JSON implementation in C'

extra:
  recipe-maintainers:
    - ocefpaf
    - sodre
