{% set version = "0.13.1-20180305" %}

package:
  name: json-c
  version: {{ version.split('-')[0] }}

source:
  url: https://github.com/json-c/json-c/archive/json-c-{{ version }}.tar.gz
  sha256: 5d867baeb7f540abe8f3265ac18ed7a24f91fe3c5f4fd99ac3caba0708511b90
  patches:
    - 00-add-library-inc.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - cmake  # [win]
  host:
    - msinttypes  # [win and vc<=9]

test:
  commands:
    - test -f ${PREFIX}/lib/libjson-c.a  # [unix]
    - test -f ${PREFIX}/lib/libjson-c${SHLIB_EXT}  # [not win]

    - if not exist %LIBRARY_BIN%/json-c.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%/json-c.lib exit 1  # [win]

about:
  home: https://github.com/json-c/json-c/wiki
  license: MIT
  license_file: COPYING
  summary: 'A JSON implementation in C.'

extra:
  recipe-maintainers:
    - ocefpaf
    - sodre
