# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Uz6ZMub3bjMdk3K/lWyG1dAGkO6vHh5/qaUk0iPcsdj72KwY7IFv+rMEaBE3QEWohzTVGzOaV8IMnEyLC8UvMFZHfqJEhiXrtjOA/1igbE+x/mJi4++zw5WYId31jmPVvarTzubfoTDMHSSp39r1kIMgtdATo37NQLdZraDv8a6Qx6stK9J0viJmvJyIU6lMNhbgge10sC9KC/VubBYxWfcgZSaWNOIMnEaMvXSlMGJskBNO24jPwn/d/1XQj69Yx5Nwb964M/rGYqnThTwjKR2krFSFf9mpxYn1YmGH27coS4sh9dJfprACDBuzHBseZrisnmxi+uXEEyLPHasp04pv4grCGMRoQnJH9mCLQ9nwgScG7lpQPrXEOz7uiwQ1Jn9myt/4GIml4tRk7mpjygfRnPLe4XMpCF6qsYoI0ry3Gl/s4XHdlgm77bMEhw0VO+SSy79f3F7aPkyUFIJYjKaaCTHN1z0DVDcWC71YQLGuGe0Ss+zIqiNBjCIyFsne9U4oI9ILHGGRKjHAldHKGlYe94A+PckXJ7PICMJFzIroLQEO9iEyIKiwST5QanlwisoGGVlRjuc2yRf/PDWRm1+4fkV7D2luGEZ4DidYPJWraBvITcicP+U4j4pZ9KmpvAUDSt3+87lOli705GpkbPxn2DvCy+0uiq+VG30MpTk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml

  - conda config --remove channels defaults --force

  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
