travis:
  secure:
    BINSTAR_TOKEN: Uz6ZMub3bjMdk3K/lWyG1dAGkO6vHh5/qaUk0iPcsdj72KwY7IFv+rMEaBE3QEWohzTVGzOaV8IMnEyLC8UvMFZHfqJEhiXrtjOA/1igbE+x/mJi4++zw5WYId31jmPVvarTzubfoTDMHSSp39r1kIMgtdATo37NQLdZraDv8a6Qx6stK9J0viJmvJyIU6lMNhbgge10sC9KC/VubBYxWfcgZSaWNOIMnEaMvXSlMGJskBNO24jPwn/d/1XQj69Yx5Nwb964M/rGYqnThTwjKR2krFSFf9mpxYn1YmGH27coS4sh9dJfprACDBuzHBseZrisnmxi+uXEEyLPHasp04pv4grCGMRoQnJH9mCLQ9nwgScG7lpQPrXEOz7uiwQ1Jn9myt/4GIml4tRk7mpjygfRnPLe4XMpCF6qsYoI0ry3Gl/s4XHdlgm77bMEhw0VO+SSy79f3F7aPkyUFIJYjKaaCTHN1z0DVDcWC71YQLGuGe0Ss+zIqiNBjCIyFsne9U4oI9ILHGGRKjHAldHKGlYe94A+PckXJ7PICMJFzIroLQEO9iEyIKiwST5QanlwisoGGVlRjuc2yRf/PDWRm1+4fkV7D2luGEZ4DidYPJWraBvITcicP+U4j4pZ9KmpvAUDSt3+87lOli705GpkbPxn2DvCy+0uiq+VG30MpTk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
